---
# tasks file for roles/database
  - name: Run Database
    docker_container:
      name: database
      networks: 
      - name: app-network
      env:
        POSTGRES_DB: "tp_db"
        POSTGRES_USER: "exampleuser"
        POSTGRES_PASSWORD: "examplepassword"
      image: awakeduck/takima_database:latest
