---
# tasks file for roles/proxy
  - name: Run HTTPD
    docker_container:
      name: httpd
      networks:
      - name: app-network
      image: awakeduck/takima_http_server:latest
      published_ports:
      - 80:80
